
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[334] =
    {   0,
        0,    0,   95,   93,    3,    3,   80,   93,   69,   93,
       93,   85,   86,   67,   65,   87,   66,   83,   68,    5,
        5,   91,   88,   75,   64,   74,   92,   81,   82,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   89,   93,   90,    3,
       73,    0,    4,    0,   78,    0,    0,    8,    0,    0,
       70,   71,    5,    6,    0,    0,    0,    5,   92,   92,
       77,   72,   76,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   37,   92,   92,   92,   92,   92,   92,
       92,   21,   92,   92,   92,   92,   92,   92,   92,   92,

       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   79,    4,    0,    7,    0,    7,    0,    6,
        0,    0,    0,    2,    0,    5,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   20,   92,   92,   92,   23,   92,
       92,   92,   25,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   60,   61,
       92,   92,   92,    9,    0,    6,    1,   92,   92,   92,
       92,   34,   12,   92,   13,   92,   92,   92,   92,   92,
       18,   38,   92,   92,   92,   92,   43,   92,   92,   92,

       92,   24,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   56,   92,   92,   30,
       92,   92,    0,    6,   92,   92,   92,   11,   35,   14,
       36,   92,   92,   92,   92,   92,   41,   19,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       52,   92,   92,   54,   92,   92,   57,   92,   92,   31,
       84,    6,   92,   33,   92,   92,   92,   17,   92,   92,
       92,   92,   45,   92,   92,   47,   48,   92,   92,   92,
       26,   92,   27,   28,   92,   29,   92,   58,   92,   92,
        6,   92,   10,   92,   16,   39,   40,   42,   92,   92,

       92,   49,   63,   92,   92,   92,   92,   92,   92,    6,
       32,   15,   92,   92,   92,   92,   51,   53,   92,   92,
       62,   92,   92,   46,   50,   92,   59,   44,   22,   92,
       92,   55,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   25,   25,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,   28,   29,    1,    1,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   26,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    1,    4,    4,    1,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[340] =
    {   0,
        0,    0,  666,  667,   56,   59,  642,   58,  667,  656,
       59,  615,  667,  667,  649,  667,   51,   53,   61,   58,
       63,  667,  667,  638,  637,  636,  642,  667,  667,   59,
       51,   68,   69,   67,   75,   73,   79,   80,   83,  101,
      106,  108,  109,  113,  111,   64,  667,  601,  667,  130,
      667,  133,  667,  137,  667,  119,  647,  121,  139,  602,
      667,  667,   74,  119,  642,  160,  150,  154,  637,  158,
      667,  667,  667,  124,  128,  135,  150,  137,  163,   72,
      164,  140,  165,  170,  171,  179,  181,  180,  183,  185,
      182,  636,  188,  186,  193,  187,  189,  190,  191,  200,

      196,  197,  201,  220,  205,  208,  198,  223,  232,  231,
      235,  236,  667,  248,  244,  250,  251,  667,  607,  237,
      638,  246,  261,  667,  264,    0,  254,  255,  264,  265,
      266,  267,  271,  268,  270,  272,  275,  276,  274,  277,
      278,  281,  280,  282,  633,  283,  290,  293,  295,  300,
      297,  306,  632,  308,  307,  311,  309,  312,  315,  316,
      318,  322,  319,  321,  323,  324,  327,  326,  631,  630,
      332,  342,  334,  345,  611,  333,  667,  329,  340,  347,
      351,  628,  627,  360,  626,  361,  362,  363,  364,  366,
      625,  624,  368,  367,  371,  369,  623,  373,  372,  375,

      376,  622,  379,  377,  382,  386,  387,  388,  399,  378,
      380,  404,  407,  383,  409,  414,  621,  384,  415,  620,
      416,  418,  624,  425,  417,  420,  424,  618,  617,  616,
      615,  429,  430,  422,  432,  433,  434,  614,  437,  439,
      441,  442,  445,  447,  449,  443,  444,  456,  451,  453,
      613,  457,  459,  612,  466,  468,  470,  474,  477,  611,
      667,  480,  476,  610,  478,  480,  484,  609,  486,  488,
      485,  489,  599,  490,  494,  598,  594,  493,  497,  495,
      590,  500,  587,  586,  502,  585,  503,  584,  505,  509,
      522,  510,  583,  514,  582,  581,  580,  579,  512,  526,

      520,  578,  577,  528,  529,  531,  535,  537,  534,  667,
      574,  573,  539,  540,  547,  541,  566,  564,  548,  543,
      562,  545,  549,  557,  556,  550,  554,  553,  199,  551,
      555,  192,  667,  604,  608,   96,  612,  616,  620
    } ;

static const flex_int16_t yy_def[340] =
    {   0,
      333,    1,  333,  333,  333,  333,  333,  334,  333,  333,
      335,  333,  333,  333,  333,  333,  333,  333,  333,  336,
      336,  333,  333,  333,  333,  333,  336,  333,  333,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  333,  333,  333,  333,
      333,  334,  333,  334,  333,  337,  333,  337,  337,  333,
      333,  333,  333,  333,  338,  339,  333,  336,  336,  336,
      333,  333,  333,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  333,  334,  337,  337,  337,  333,  333,  333,
      338,  338,  339,  333,  339,   70,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  337,  333,  333,  333,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  333,  333,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      333,  333,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      333,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  336,  333,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,    0,  333,  333,  333,  333,  333,  333
    } ;

static const flex_int16_t yy_nxt[725] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   28,    4,   29,   30,
       31,   32,   33,   34,   35,   36,   27,   37,   27,   38,
       39,   40,   27,   41,   27,   42,   43,   44,   27,   45,
       46,   27,   27,   27,   47,   48,   49,   50,   50,   50,
       50,   50,   50,   53,   57,   62,  333,   58,   63,   63,
       64,   64,   65,   67,  333,   68,   68,   66,   67,  333,
       68,   68,  333,  333,  333,   54,   59,  333,  333,   74,
      333,   63,   63,   76,  333,  333,   77,   79,  333,   69,

      112,  134,   83,   78,   80,   75,   85,   81,   86,   70,
       82,   84,   88,   92,   89,   91,  333,   90,   87,   93,
       94,  333,   95,  333,  333,   96,  333,  116,  333,  116,
       97,   50,   50,   50,   98,   99,  120,  120,   53,  333,
      110,  102,  114,  333,  115,  103,  117,  116,  117,  108,
      333,  100,  333,  111,  101,  333,  104,  105,  109,  106,
       54,  107,  124,  125,   54,  333,  117,   64,   64,   67,
      127,   68,   68,  333,  128,  126,  126,  129,  333,  333,
      333,  136,  126,  130,  131,  333,  333,  126,  126,  126,
      126,  126,  126,  135,  333,  333,  333,  333,  333,  137,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  132,
      133,  333,  333,  333,  333,  333,  333,  139,  138,  151,
      333,  143,  154,  333,  141,  144,  157,  140,  142,  146,
      145,  147,  148,  149,  150,  333,  152,  155,  333,  165,
      153,  158,  156,  160,  159,  164,  333,  333,  163,  161,
      333,  333,  174,   53,  176,  176,  115,  122,  174,  174,
      166,  168,  177,  124,  125,  162,  124,  125,  167,  333,
      333,  117,  171,  173,  172,   54,  170,  117,  117,  333,
      333,  333,  333,  333,  169,  333,  333,  333,  179,  333,
      333,  333,  333,  333,  181,  333,  333,  333,  333,  182,

      183,  178,  184,  180,  189,  333,  190,  191,  333,  195,
      333,  196,  333,  185,  194,  333,  186,  192,  187,  188,
      193,  333,  333,  333,  333,  197,  333,  333,  201,  198,
      333,  333,  199,  333,  333,  202,  333,  333,  333,  333,
      200,  333,  333,  204,  333,  203,  205,  333,  208,  333,
      224,  224,  214,  174,  216,  333,  206,  333,  207,  213,
      209,  211,  333,  210,  220,  212,  333,  219,  215,  218,
      217,  221,  117,  222,  225,  333,  333,  333,  333,  333,
      227,  333,  333,  333,  333,  226,  333,  333,  333,  228,
      333,  333,  333,  333,  333,  333,  229,  333,  333,  333,

      232,  333,  333,  333,  241,  234,  239,  230,  236,  231,
      237,  245,  233,  235,  333,  246,  238,  240,  243,  333,
      247,  242,  333,  250,  333,  248,  244,  251,  254,  333,
      333,  333,  333,  333,  257,  333,  249,  333,  253,  333,
      255,  252,  262,  262,  333,  333,  263,  333,  333,  333,
      256,  260,  333,  265,  333,  268,  333,  333,  333,  333,
      333,  258,  333,  259,  333,  270,  333,  264,  333,  267,
      266,  333,  333,  271,  333,  280,  275,  272,  276,  269,
      277,  333,  274,  333,  278,  333,  273,  281,  284,  333,
      279,  333,  333,  333,  283,  333,  282,  291,  291,  333,

      333,  333,  286,  333,  333,  333,  285,  292,  333,  333,
      333,  289,  333,  287,  290,  333,  288,  333,  333,  293,
      333,  300,  299,  301,  333,  333,  302,  333,  294,  333,
      303,  295,  296,  305,  297,  333,  306,  298,  308,  310,
      310,  333,  304,  333,  333,  307,  333,  312,  309,  333,
      333,  315,  333,  313,  333,  333,  333,  311,  333,  314,
      333,  316,  333,  333,  333,  333,  333,  321,  333,  333,
      333,  333,  333,  325,  318,  317,  319,  333,  320,  333,
      324,  333,  323,  329,  331,  326,  322,  332,  333,  333,
      327,  328,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  330,   52,  333,   52,   52,   56,  333,
       56,   56,  115,  333,  333,  115,  121,  121,  121,  121,
      123,  123,  123,  123,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  261,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  223,  333,  333,  333,  333,  122,
      175,  333,  333,  122,  119,  118,  113,  333,   73,   72,
       71,   61,   60,   55,   51,  333,    3,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333
    } ;

static const flex_int16_t yy_chk[725] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        6,    6,    6,    8,   11,   17,   31,   11,   17,   17,
       18,   18,   19,   20,   30,   20,   20,   19,   21,   46,
       21,   21,   34,   32,   33,    8,   11,   80,   36,   30,
       35,   63,   63,   31,   37,   38,   31,   32,   39,  336,

       46,   80,   33,   31,   32,   30,   34,   32,   34,   20,
       32,   33,   35,   37,   35,   36,   40,   35,   34,   37,
       37,   41,   38,   42,   43,   39,   45,   56,   44,   58,
       40,   50,   50,   50,   40,   41,   64,   64,   52,   74,
       45,   42,   54,   75,   59,   43,   56,   59,   58,   44,
       76,   41,   78,   45,   41,   82,   43,   43,   44,   43,
       52,   43,   66,   66,   54,   77,   59,   67,   67,   68,
       74,   68,   68,   70,   75,   70,   70,   76,   79,   81,
       83,   82,   70,   77,   78,   84,   85,   70,   70,   70,
       70,   70,   70,   81,   86,   88,   87,   91,   89,   83,

       90,   94,   96,   93,   97,   98,   99,  332,   95,   79,
       79,  101,  102,  107,  329,  100,  103,   85,   84,   96,
      105,   88,   99,  106,   87,   89,  101,   86,   87,   91,
       90,   93,   94,   94,   95,  104,   97,  100,  108,  107,
       98,  102,  100,  103,  102,  106,  110,  109,  105,  104,
      111,  112,  115,  114,  120,  120,  117,  122,  116,  117,
      108,  109,  122,  123,  123,  104,  125,  125,  108,  127,
      128,  115,  111,  112,  111,  114,  110,  116,  117,  129,
      130,  131,  132,  134,  109,  135,  133,  136,  128,  139,
      137,  138,  140,  141,  130,  143,  142,  144,  146,  131,

      132,  127,  133,  129,  137,  147,  138,  139,  148,  143,
      149,  144,  151,  134,  142,  150,  135,  140,  136,  136,
      141,  152,  155,  154,  157,  146,  156,  158,  149,  147,
      159,  160,  147,  161,  163,  150,  164,  162,  165,  166,
      148,  168,  167,  152,  178,  151,  154,  171,  157,  173,
      176,  176,  163,  174,  165,  179,  155,  172,  156,  162,
      158,  160,  180,  159,  171,  161,  181,  168,  164,  167,
      166,  172,  174,  173,  178,  184,  186,  187,  188,  189,
      180,  190,  194,  193,  196,  179,  195,  199,  198,  181,
      200,  201,  204,  210,  203,  211,  184,  205,  214,  218,

      188,  206,  207,  208,  200,  190,  198,  186,  194,  187,
      195,  205,  189,  193,  209,  206,  196,  199,  203,  212,
      207,  201,  213,  210,  215,  208,  204,  211,  214,  216,
      219,  221,  225,  222,  218,  226,  209,  234,  213,  227,
      215,  212,  224,  224,  232,  233,  225,  235,  236,  237,
      216,  222,  239,  227,  240,  234,  241,  242,  246,  247,
      243,  219,  244,  221,  245,  236,  249,  226,  250,  233,
      232,  248,  252,  237,  253,  247,  242,  239,  243,  235,
      244,  255,  241,  256,  245,  257,  240,  248,  252,  258,
      246,  263,  259,  265,  250,  266,  249,  262,  262,  267,

      271,  269,  255,  270,  272,  274,  253,  263,  278,  275,
      280,  258,  279,  256,  259,  282,  257,  285,  287,  265,
      289,  274,  272,  275,  290,  292,  278,  299,  266,  294,
      279,  267,  269,  282,  270,  301,  285,  271,  289,  291,
      291,  300,  280,  304,  305,  287,  306,  294,  290,  309,
      307,  301,  308,  299,  313,  314,  316,  292,  320,  300,
      322,  304,  315,  319,  323,  326,  330,  309,  328,  327,
      331,  325,  324,  316,  306,  305,  307,  321,  308,  318,
      315,  317,  314,  323,  330,  319,  313,  331,  312,  311,
      320,  322,  303,  302,  298,  297,  296,  295,  293,  288,

      286,  284,  283,  326,  334,  281,  334,  334,  335,  277,
      335,  335,  337,  276,  273,  337,  338,  338,  338,  338,
      339,  339,  339,  339,  268,  264,  260,  254,  251,  238,
      231,  230,  229,  228,  223,  220,  217,  202,  197,  192,
      191,  185,  183,  182,  175,  170,  169,  153,  145,  121,
      119,   92,   69,   65,   60,   57,   48,   27,   26,   25,
       24,   15,   12,   10,    7,    3,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jzero.l"
/* -*-bison-*- */
/* Simple wc implementation in Flex */
#line 6 "jzero.l"
#include "defs.h"

//int rows = 0, words = 0, chars = 0;
#line 721 "lex.yy.c"
#line 722 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 15 "jzero.l"

#line 17 "jzero.l"
	//\n		rows++;

#line 944 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 334 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 667 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 19 "jzero.l"
{ /* Ignore multiline comments*/ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 20 "jzero.l"
{ /* Ignore single-line comments */; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 21 "jzero.l"
{ /* Remove whitespace */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 23 "jzero.l"
{ return STRING_LITERAL; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 24 "jzero.l"
{ return INTEGER_LITERAL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "jzero.l"
{ return FLOAT_LITERAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 26 "jzero.l"
{ return CHARACTER_LITERAL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "jzero.l"
{ return CHAR_ERROR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 29 "jzero.l"
{ return CHAR_ERROR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "jzero.l"
{ return BOOLEAN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "jzero.l"
{ return BREAK; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "jzero.l"
{ return CASE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "jzero.l"
{ return CHAR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "jzero.l"
{ return CLASS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "jzero.l"
{ return CONTINUE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "jzero.l"
{ return DEFAULT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "jzero.l"
{ return DOUBLE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "jzero.l"
{ return ELSE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "jzero.l"
{ return FLOAT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "jzero.l"
{ return FOR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "jzero.l"
{ return IF; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "jzero.l"
{ return INSTANCEOF; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "jzero.l"
{ return INT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "jzero.l"
{ return LONG; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "jzero.l"
{ return NEW; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "jzero.l"
{ return PUBLIC; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "jzero.l"
{ return RETURN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "jzero.l"
{ return STATIC; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "jzero.l"
{ return SWITCH; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "jzero.l"
{ return VOID; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "jzero.l"
{ return WHILE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 54 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 55 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 56 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 57 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 58 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 59 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 60 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 61 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 62 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 63 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 64 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 65 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 66 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 67 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 68 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 69 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 70 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 71 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 72 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 73 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 74 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 75 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 76 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 77 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 78 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 79 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 80 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 81 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 82 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 83 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 84 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 85 "jzero.l"
{ return NOT_RESERVED; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "jzero.l"
{ return ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 88 "jzero.l"
{ return ADD; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 89 "jzero.l"
{ return SUB; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "jzero.l"
{ return MULTIPLY; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "jzero.l"
{ return DIVIDE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "jzero.l"
{ return MODULO; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "jzero.l"
{ return INCREMENT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "jzero.l"
{ return DECREMENT; }
	YY_BREAK
/* "-"             	{ return NEGATION; }*/
case 72:
YY_RULE_SETUP
#line 96 "jzero.l"
{ return EQUAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 97 "jzero.l"
{ return NOT_EQUAL; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 98 "jzero.l"
{ return GREATER_THAN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 99 "jzero.l"
{ return LESS_THAN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 100 "jzero.l"
{ return GREATER_EQUAL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 101 "jzero.l"
{ return LESS_EQUAL; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 102 "jzero.l"
{ return LOGIC_AND; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 103 "jzero.l"
{ return LOGIC_OR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 104 "jzero.l"
{ return LOGIC_NOT; }
	YY_BREAK
/*"instanceof"    	{ return INSTANCEOF; }*/
case 81:
YY_RULE_SETUP
#line 106 "jzero.l"
{ return LEFT_SUBSCRIPT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 107 "jzero.l"
{ return RIGHT_SUBSCRIPT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 108 "jzero.l"
{ return DOT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 109 "jzero.l"
{ return TYPE_CAST; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 110 "jzero.l"
{ return LEFT_PARENTHESIS; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 111 "jzero.l"
{ return RIGHT_PARENTHESIS; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 112 "jzero.l"
{ return COMMA; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 113 "jzero.l"
{ return SEMI_COLON; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 114 "jzero.l"
{ return LEFT_BRACKET; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 115 "jzero.l"
{ return RIGHT_BRACKET; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 116 "jzero.l"
{ return COLON; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 118 "jzero.l"
{ return WORD_CODE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 119 "jzero.l"
{ return UNKNOWN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 121 "jzero.l"
ECHO;
	YY_BREAK
#line 1476 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 334 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 334 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 333);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 121 "jzero.l"


