#ifndef DEFS_H_
#define DEFS_H_

//jzero.l variables
extern int rows, words, chars;
extern FILE *yyin;
extern int yylex();
extern char *yytext;
extern int yylineno;

typedef enum {
	TOKEN = 500,
	PR_CLASSBODYDECLS,
	PR_VARDECLS,
	PR_METHODDECL,
	PR_METHODHEADER,
	PR_FORMALPARMLIST,
	PR_FORMALPARM,
	PR_CONSTRUCTORDECL,
	PR_BLOCKSTMTS,
	PR_LOCALVARDECL,
	PR_IF_THEN_STMT,
	PR_IF_THEN_ELSE_STMT,
	PR_IF_ELSEIF_STMT,
	PR_IF_ELSEIF_ELSE_STMT,
	PR_ELSE_IF_SEQUENCE,
	PR_WHILE_STMT,
	PR_FOR_STMT,
	PR_STMT_EXPR_LIST,
	PR_INSTANTIATION_EXPR,
	PR_ARG_LIST,
	PR_METHODCALL_P,
	PR_METHODCALL_B,
	PR_METHODCALL_PP,
	PR_METHODCALL_BB,
	PR_MUL_EXPR_MULT,
	PR_MUL_EXPR_DIV,
	PR_MUL_EXPR_MOD,
	PR_ADD_EXPR_ADD,
	PR_ADD_EXPR_SUB,
	PR_REL_EXPR,
	PR_EQ_EXPR,
	PR_EQ_EXPR_NOT,
	PR_COND_AND_EXPR,
	PR_COND_OR_EXPR,
	PR_ASSIGNMENT,
} prodrule;

#endif
